name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: 构建
    runs-on: windows-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 配置 .Net 环境
        uses: actions/setup-dotnet@v4.0.0
        with:
          global-json-file: ./global.json
          cache: false

      - name: 还原
        shell: pwsh
        run: dotnet restore

      - name: 构建
        shell: pwsh
        run: dotnet build VRCFaceTracking.PicoConnect --graph --configuration Release --no-restore

      - name: 发布
        shell: pwsh
        run: dotnet publish VRCFaceTracking.PicoConnect --graph --configuration Release --no-build --no-restore --output artifacts

      - name: 生成校验和
        shell: pwsh
        run: |
          Write-Output "### Build Success :rocket: $env:matrix_os" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|File|SHA256|" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|:-|:-:|" >> $env:GITHUB_STEP_SUMMARY
          Get-ChildItem artifacts | ForEach-Object {
            Write-Output "|$($PSItem.Name)|$((Get-FileHash $PSItem -Algorithm SHA256).Hash)|" >> $env:GITHUB_STEP_SUMMARY
          }

      - name: 收集 Nuget 包
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build
          path: |
            artifacts/*
          retention-days: 3
